# Generated by Django 4.1.2 on 2023-01-23 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_yearopeningnumbers_end_debit_note_bill_no_and_more'),
        ('tools_management', '0009_toolswithout_details_toolswithout_materials'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depit_note_materials',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_data', to='master.tools'),
        ),
        migrations.AlterField(
            model_name='depit_note_materials',
            name='without_materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='without_material_reference', to='tools_management.toolswithout_materials'),
        ),
    ]
