# Generated by Django 4.1.2 on 2023-01-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_depit_note_materials_tool_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depit_note_invoice',
            old_name='company_id',
            new_name='company',
        ),
    ]
