# Generated by Django 4.1.2 on 2023-01-27 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_company_id_depit_note_invoice_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_details',
            name='account_type',
            field=models.IntegerField(choices=[(1, 'Sb'), (2, 'Ca'), (3, 'Loan')], default=1),
        ),
        migrations.AddField(
            model_name='bank_details',
            name='ln',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='loan_paymentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.IntegerField(choices=[(1, 'Cash'), (2, 'Bank')], default=1)),
                ('close', models.BooleanField(default=False)),
                ('bank_i', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_refno', models.CharField(default=None, max_length=60, null=True)),
                ('premium_amount', models.FloatField(default=0)),
                ('loan', models.BooleanField(default=False)),
                ('inte_amount', models.FloatField(default=0)),
                ('balance_amount', models.FloatField(default=0)),
                ('ln', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0, null=True)),
                ('payment_refdate', models.DateField(blank=True, default=None, null=True)),
                ('payment_date', models.DateField(null=True)),
                ('financial_period', models.DateField(auto_now=True)),
                ('tenant_id', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('bank_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ba_details', to='accounts.bank_details')),
            ],
        ),
    ]
