# Generated by Django 4.1.2 on 2023-02-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bank_details_ln_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_ledger',
            name='financial_period',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='general_ledger',
            name='tenant_id',
            field=models.IntegerField(default=1),
        ),
    ]
