# Generated by Django 4.1.2 on 2023-03-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_general_ledger_financial_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_ledger',
            name='tenant_id',
            field=models.IntegerField(),
        ),
    ]
